version: "3.7"
services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: consultorio-app
    container_name: consultorio-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - consultorio-network

  db:
    image: mysql:8.0
    container_name: consultorio-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - consultorio-network

  nginx:
    image: nginx:alpine
    container_name: consultorio-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - consultorio-network

  npm:
    image: node:20-alpine
    container_name: consultorio-npm
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: [ 'npm' ]
    networks:
      - consultorio-network

  redis:
    image: redis:alpine
    container_name: consultorio-redis
    networks:
      - consultorio-network

  mailpit:
    image: axllent/mailpit
    container_name: consultorio-mailpit
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - consultorio-network

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: consultorio-pma
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - consultorio-network

networks:
  consultorio-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
